apiVersion: v1
kind: Service
metadata:
  name: doldolseo-review-rest
  namespace: rest
spec:
  selector:
   app: openjdk_review
  ports:
    - name: tomcat
      protocol : TCP
      port : 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doldolseo-review-rest
  namespace: rest
spec:
  selector:
    matchLabels:
      app: openjdk_review
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: openjdk_review
    spec:
      containers:
      - name: openjdk
        image: kki7823/doldolseo-rest-review:1.1.2arm
        #image: kki7823/doldolseo-rest-review:1.1.2amd
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /doldolseo/src/main/resources/static
          name: review-resource-volume
      volumes:
      - name: review-resource-volume
        hostPath:
          path: /mnt/volumes-rest-resource/doldolseo-review-resource
          type: Directory
