apiVersion: v1
kind: Service
metadata:
  name: doldolseo-member-db
  namespace: db
spec:
  selector:
   app: mysql_member
  ports:
    - name: mysql
      protocol : TCP
      port : 3306
      targetPort: 3306
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: doldolseo-member-db
  namespace: db
  labels:
    app: mysql_member
spec:
  containers:
  - name: doldolseo-member-db
    image: kki7823/doldolseo_db:1.4.0
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: member-volume
  volumes:
  - name: member-volume
    hostPath:
      path: /mnt/volumes/doldolseo-member-volume
      type: Directory
