apiVersion: v1
kind: Service
metadata:
  name: doldolseo-member-rest
  namespace: rest
spec:
  selector:
   app: openjdk_member
  ports:
    - name: tomcat
      protocol : TCP
      port : 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doldolseo-member-rest
  namespace: rest
spec:
  selector:
    matchLabels:
      app: openjdk_member
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: openjdk_member
    spec:
      containers:
      - name: openjdk
        image: kki7823/doldolseo-rest-member:1.3.9arm64
        #image: kki7823/doldolseo-rest-member:1.3.9amd64
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /doldolseo/src/main/resources/static
          name: gw-resource-volume
      volumes:
      - name: gw-resource-volume
        hostPath:
          path: /mnt/volumes-rest-resource/doldolseo-member-resource
          type: Directory
